using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;

namespace GTA
{
    /// <summary>
    /// Static label tables for the Menu Reader (schema v3), shipped as
    /// scripts/gta11y-menulabels.json — generated by tools/build-menulabels.py
    /// from the game's pausemenu.xml + eMenuScreen/eMenuPref enums, refined by
    /// tools/menulabels-overrides.json.
    ///
    /// v3 row model (runtime-validated 2026-07-18): settings pref-rows are
    /// keyed by (51, eMenuPref VALUE); hashed trigger rows resolve through
    /// screenItems by their joaat menuId. Rows carry screenMenuId (pane
    /// containment), kind, optionType and a status provenance flag the reader
    /// uses as an honesty gate.
    ///
    /// MapDb conventions: Load() once, never throws, lookups return false/null
    /// on miss. GXT resolves lazily via Game.GetLocalizedString (main script
    /// thread), cached; FAILED lookups retry once per menu-open (transient
    /// early-session misses must not pin raw ids for a whole session).
    /// </summary>
    public static class MenuLabelDb
    {
        public enum LabelResult { Missing, GxtFailed, Ok }

        public class TabEntry
        {
            public int index;
            public string gxt;
            public string label;
            public int? leakMenuId;
        }

        public class MenuEntry
        {
            public int menuId;
            public string uniqueName;
            public string kind;    // screen | internal | hashedTrigger
            public string gxt;
            public string label;
        }

        public class RowEntry
        {
            public int menuId;
            public int? uniqueId;      // eMenuPref value (basis: prefValue)
            public int? screenMenuId;  // owning settings pane's menu id
            public string kind;        // pref | ...
            public string optionType;  // MENU_OPTION_* (slider/toggle/list)
            public string gxt;
            public string pref;
            public string basis;
            public string status;      // assumed | verified | refuted
            public string label;
            // v1.3: key-trust model. The 2944-build enum shifts +4 for uid>=121
            // and by an unknown 0-4 for header values 47-120 on this game build.
            //   confirmed - uid in the observed set; speak plainly
            //   derived   - uid<=46 or >=121 unobserved; offset settled, speak plainly
            //   unpinned  - header value 47-120; key may be off 0-4, speak with a cue
            public string keyConfidence; // confirmed | derived | unpinned (null => derived)
            public int? ord;             // 0-based visible index within screenMenuId
            public bool conditional;     // row can be hidden (context/platform/value-gated)
        }

        public class ScreenItemEntry
        {
            public int menuId;         // joaat of hashName
            public string hashName;
            public int? screenMenuId;
            public string kind;
            public string gxt;
            public string label;
        }

        public class PhoneOverride
        {
            public string gxt;
            public string script;
            public string note;
        }

        public class PhoneSlot
        {
            public int slot;
            public string gxt;
            public string label;
            public string script;
            public List<PhoneOverride> overrides;
            public string note;
        }

        public class ProfilePref
        {
            public string name;
            public string optionType;
            public string pref;
        }

        /// <summary>v4: where a PREF_* lives in GTA's settings.xml and how to turn
        /// the stored value into speech. Graphics/video rows are NOT profile
        /// settings, so this is the only value source they have.</summary>
        public class SettingsXmlEntry
        {
            public string section;                  // graphics | video | audio | system
            public string key;                      // element name inside that section
            public string mode;                     // index | lookup | bool | pct | number | res
            public Dictionary<string, int> lookup;  // literal value -> optionValues index
            public string unit;                     // spoken suffix for mode=number
            public int add;                         // offset applied before speaking (mode=number)
        }

        /// <summary>v4: ordered in-app row labels for one phone app script.</summary>
        public class PhoneAppRow
        {
            public int row;
            public string gxt;
            public string label;
        }

        private static List<TabEntry> tabs = new List<TabEntry>();
        private static Dictionary<int, MenuEntry> menus = new Dictionary<int, MenuEntry>();
        private static Dictionary<long, RowEntry> rows = new Dictionary<long, RowEntry>();
        private static Dictionary<int, ScreenItemEntry> screenItems = new Dictionary<int, ScreenItemEntry>();
        private static Dictionary<int, int> leakToTab = new Dictionary<int, int>();
        private static Dictionary<string, List<PhoneSlot>> phoneHome = new Dictionary<string, List<PhoneSlot>>();
        private static Dictionary<string, string> phoneApps = new Dictionary<string, string>();
        private static Dictionary<string, string[]> optionValues = new Dictionary<string, string[]>();
        private static Dictionary<int, ProfilePref> profilePrefs = new Dictionary<int, ProfilePref>();
        private static Dictionary<string, SettingsXmlEntry> settingsXmlMap = new Dictionary<string, SettingsXmlEntry>();
        private static Dictionary<string, List<PhoneAppRow>> phoneAppRows = new Dictionary<string, List<PhoneAppRow>>();
        private static Dictionary<string, int> phoneGlobals = new Dictionary<string, int>();
        private static Dictionary<string, string> gxtCache = new Dictionary<string, string>();
        private static HashSet<string> gxtFailed = new HashSet<string>();

        private static int tabCount = 10;
        private static bool loaded = false;
        private static string loadStatus = "notLoaded";
        private static int overridesApplied = 0;
        public static bool IsLoaded { get { return loaded; } }
        public static string LoadStatus { get { return loadStatus; } }
        public static int TabCount { get { return tabCount; } }
        public static int OverridesApplied { get { return overridesApplied; } }

        public static void Load()
        {
            if (loaded) return;
            string path = "scripts/gta11y-menulabels.json";
            try
            {
                if (!File.Exists(path))
                {
                    loadStatus = "fileNotFound";
                    loaded = true;
                    return;
                }
                var root = JsonConvert.DeserializeObject<LabelJsonRoot>(File.ReadAllText(path));
                if (root == null)
                {
                    loadStatus = "nullData";
                    loaded = true;
                    return;
                }
                if (root.tabCount > 0) tabCount = root.tabCount;
                if (root.tabs != null)
                {
                    tabs = root.tabs;
                    foreach (var t in root.tabs)
                        if (t.leakMenuId.HasValue) leakToTab[t.leakMenuId.Value] = t.index;
                }
                if (root.menus != null)
                    foreach (var m in root.menus)
                        if (!menus.ContainsKey(m.menuId)) menus[m.menuId] = m;
                if (root.rows != null)
                    foreach (var r in root.rows)
                    {
                        if (!r.uniqueId.HasValue) continue;
                        rows[RowKey(r.menuId, r.uniqueId.Value)] = r; // last-wins
                        if (r.status == "verified") overridesApplied++;
                    }
                if (root.screenItems != null)
                    foreach (var s in root.screenItems)
                        if (!screenItems.ContainsKey(s.menuId)) screenItems[s.menuId] = s;
                if (root.optionValues != null) optionValues = root.optionValues;
                if (root.profilePrefs != null)
                    foreach (var kv in root.profilePrefs)
                    {
                        int id;
                        if (int.TryParse(kv.Key, out id)) profilePrefs[id] = kv.Value;
                    }
                if (root.phoneHome != null) phoneHome = root.phoneHome;
                if (root.phoneApps != null) phoneApps = root.phoneApps;
                if (root.settingsXmlMap != null) settingsXmlMap = root.settingsXmlMap;
                if (root.phoneAppRows != null) phoneAppRows = root.phoneAppRows;
                if (root.phoneGlobals != null) phoneGlobals = root.phoneGlobals;
                loadStatus = "ok(v" + root.version + ")";
                loaded = true;
            }
            catch (Exception ex)
            {
                loadStatus = MapDb.FmtLoadError(ex);
                loaded = true;
            }
        }

        private static long RowKey(int menuId, int uniqueId)
        {
            return ((long)menuId << 32) | (uint)uniqueId;
        }

        /// <summary>Retry failed GXT lookups on the next menu open — one bad
        /// early-session lookup must not pin fallbacks for the session.</summary>
        public static void RetryFailedGxt()
        {
            foreach (var key in gxtFailed) gxtCache.Remove(key);
            gxtFailed.Clear();
        }

        private static string Resolve(string gxt, string label)
        {
            if (!string.IsNullOrEmpty(gxt))
            {
                string txt;
                if (!gxtCache.TryGetValue(gxt, out txt))
                {
                    try { txt = Game.GetLocalizedString(gxt); }
                    catch { txt = null; }
                    // reject empties, the literal NULL, and strings carrying
                    // GTA formatting tokens (~a~, ~1~ ...) — not speakable
                    if (txt != null && (txt.Length == 0 || txt == "NULL" || txt.IndexOf('~') >= 0)) txt = null;
                    gxtCache[gxt] = txt;
                    if (txt == null) gxtFailed.Add(gxt);
                }
                if (txt != null) return txt;
            }
            if (!string.IsNullOrEmpty(label)) return label;
            return null;
        }

        public static string TabName(int index)
        {
            foreach (var t in tabs)
            {
                if (t.index != index) continue;
                return Resolve(t.gxt, t.label) ?? ("tab " + index);
            }
            return "tab " + index;
        }

        public static bool TryTabForLeakId(int menuId, out int tabIndex)
        {
            return leakToTab.TryGetValue(menuId, out tabIndex);
        }

        /// <summary>True when this menuId must never be spoken (transition
        /// sentinels, INCEPT_TRIGGER and friends).</summary>
        public static bool IsInternal(int menuId)
        {
            MenuEntry m;
            return menus.TryGetValue(menuId, out m) && m.kind == "internal";
        }

        public static bool TryMenuLabel(int menuId, out string label)
        {
            label = null;
            MenuEntry m;
            if (!menus.TryGetValue(menuId, out m) || m.kind == "internal") return false;
            label = Resolve(m.gxt, m.label);
            return label != null;
        }

        /// <summary>Hashed trigger rows (Restore Defaults, Quick Scan...):
        /// first-class label + owning pane.</summary>
        public static bool TryHashedItem(int menuId, out string label, out int screenMenuId)
        {
            label = null; screenMenuId = 0;
            ScreenItemEntry s;
            if (!screenItems.TryGetValue(menuId, out s)) return false;
            label = Resolve(s.gxt, s.label);
            screenMenuId = s.screenMenuId ?? 0;
            return label != null;
        }

        public static bool TryGetRow(int menuId, int uniqueId, out RowEntry row)
        {
            return rows.TryGetValue(RowKey(menuId, uniqueId), out row);
        }

        /// <summary>Tri-state row label lookup so the calibration harvest can
        /// distinguish a missing entry from a GXT resolution failure.</summary>
        public static LabelResult TryRowLabel(int menuId, int uniqueId, out string label, out RowEntry row)
        {
            label = null;
            if (!rows.TryGetValue(RowKey(menuId, uniqueId), out row)) return LabelResult.Missing;
            label = Resolve(row.gxt, row.label);
            return label != null ? LabelResult.Ok : LabelResult.GxtFailed;
        }

        /// <summary>Localized label for an option value (list settings):
        /// optionType + committed integer -> "Headphones" etc.</summary>
        public static bool TryOptionValueLabel(string optionType, int value, out string label)
        {
            label = null;
            string[] vals;
            if (optionType == null || !optionValues.TryGetValue(optionType, out vals)) return false;
            if (value < 0 || value >= vals.Length) return false;
            label = Resolve(vals[value], null);
            return label != null;
        }

        public static bool TryProfileName(int id, out string name)
        {
            name = null;
            ProfilePref p;
            if (profilePrefs.TryGetValue(id, out p) && !string.IsNullOrEmpty(p.name))
            {
                name = p.name;
                return true;
            }
            return false;
        }

        public static bool TryProfilePref(int id, out ProfilePref pref)
        {
            return profilePrefs.TryGetValue(id, out pref);
        }

        /// <summary>Reverse map PREF_* name -> profile-setting id, for rows
        /// whose committed value can be spoken on focus. Grows as commit-diff
        /// calibration fills the overrides file.</summary>
        public static bool TryProfileIdForPref(string pref, out int id)
        {
            id = 0;
            if (pref == null) return false;
            foreach (var kv in profilePrefs)
            {
                if (kv.Value != null && pref.Equals(kv.Value.pref, StringComparison.Ordinal))
                {
                    id = kv.Key;
                    return true;
                }
            }
            return false;
        }

        private static PhoneSlot FindSlot(string movie, int row)
        {
            List<PhoneSlot> grid;
            if (movie == null || !phoneHome.TryGetValue(movie, out grid)) return null;
            foreach (var s in grid)
                if (s.slot == row) return s;
            return null;
        }

        public static string PhoneHomeLabel(string movie, int row)
        {
            var s = FindSlot(movie, row);
            return s == null ? null : Resolve(s.gxt, s.label);
        }

        public static string PhoneHomeScript(string movie, int row)
        {
            var s = FindSlot(movie, row);
            return s == null ? null : s.script;
        }

        /// <summary>True when 'script' opening from this slot is a KNOWN
        /// mission-context override (not a table error).</summary>
        public static bool IsKnownSlotOverride(string movie, int row, string script)
        {
            var s = FindSlot(movie, row);
            if (s == null || s.overrides == null || script == null) return false;
            foreach (var o in s.overrides)
                if (string.Equals(o.script, script, StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        public static string PhoneAppLabel(string script)
        {
            string label;
            if (script != null && phoneApps.TryGetValue(script, out label)) return label;
            return null;
        }

        /// <summary>v4: label for a row INSIDE a phone app whose row list is static
        /// (Phone Settings, Internet, Checklist...). Returns null when the app has
        /// no table yet, which is the honest "row N" fallback — the reader must
        /// never invent an in-app label.</summary>
        public static string PhoneAppRowLabel(string script, int row)
        {
            List<PhoneAppRow> list;
            if (script == null || !phoneAppRows.TryGetValue(script, out list) || list == null)
                return null;
            foreach (var r in list)
                if (r.row == row) return Resolve(r.gxt, r.label);
            return null;
        }

        public static bool HasPhoneAppRows(string script)
        {
            List<PhoneAppRow> list;
            return script != null && phoneAppRows.TryGetValue(script, out list)
                   && list != null && list.Count > 0;
        }

        /// <summary>v4: a pinned PhoneGlobals offset (charSheetBase / rowMapBase /
        /// stride), so a session that identifies them is a DATA edit, not a
        /// rebuild. Returns false when unpinned -> PhoneGlobals scans instead.</summary>
        public static bool TryPhoneGlobal(string name, out int value)
        {
            return phoneGlobals.TryGetValue(name, out value);
        }

        public static bool TrySettingsXml(string pref, out SettingsXmlEntry entry)
        {
            entry = null;
            return pref != null && settingsXmlMap.TryGetValue(pref, out entry) && entry != null;
        }

        /// <summary>Localized word for an option index — the same GXT list the
        /// profile path uses, exposed so SettingsXmlDb can share it.</summary>
        public static bool TryOptionWord(string optionType, int index, out string word)
        {
            return TryOptionValueLabel(optionType, index, out word);
        }

        private class LabelJsonRoot
        {
            public int version = 0;
            public int tabCount = 0;
            public List<TabEntry> tabs = null;
            public List<MenuEntry> menus = null;
            public List<RowEntry> rows = null;
            public List<ScreenItemEntry> screenItems = null;
            public Dictionary<string, string[]> optionValues = null;
            public Dictionary<string, ProfilePref> profilePrefs = null;
            public Dictionary<string, List<PhoneSlot>> phoneHome = null;
            public Dictionary<string, string> phoneApps = null;
            public Dictionary<string, List<PhoneAppRow>> phoneAppRows = null;
            public Dictionary<string, int> phoneGlobals = null;
            public Dictionary<string, SettingsXmlEntry> settingsXmlMap = null;
        }
    }
}
